name: ci

on: push

jobs:
  dialyzer:
    strategy:
      matrix:
        elixir: ['1.11', '1.12', '1.13']

        otp: ['23.x', '24.x', '25.x']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1

        with:
          key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}

          path: _build

      - uses: erlef/setup-elixir@v1

        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - name: Run mix deps.get

        run: mix deps.get

      - name: Run mix dialyzer

        run: mix dialyzer

  test:
    strategy:
      matrix:
        elixir: ['1.11', '1.12', '1.13']

        otp: ['23.x', '24.x', '25.x']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1

        with:
          key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}

          path: _build

      - uses: erlef/setup-elixir@v1

        with:
          elixir-version: ${{ matrix.elixir }}

          otp-version: ${{ matrix.otp }}

      - name: Run mix deps.get

        run: mix deps.get

      - name: Run mix test

        run: mix test
